create extension if not exists pgcrypto;

create table if not exists creator_applications (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  first_name text not null,
  last_name text not null,
  email text not null,
  platform text not null,
  profile_url text not null,
  followers bigint,
  country text not null,
  about text not null,
  status text not null default 'pending' check (status in ('pending','approved','declined'))
);

create table if not exists creators (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  application_id uuid references creator_applications(id) on delete set null,
  display_name text not null,
  email text not null,
  creator_code text not null unique,
  commission_share numeric(5,2) not null default 25.00 check (commission_share >= 0 and commission_share <= 100),
  status text not null default 'active' check (status in ('active','paused','closed'))
);

create table if not exists referral_clicks (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  creator_id uuid not null references creators(id) on delete cascade,
  landing_path text not null
);

create table if not exists attributed_sales (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  creator_id uuid not null references creators(id) on delete restrict,
  network text not null,
  external_order_id text not null,
  gross_order_value numeric(12,2),
  luma_net_commission numeric(12,2) not null check (luma_net_commission >= 0),
  creator_share_rate numeric(5,2) not null check (creator_share_rate >= 0 and creator_share_rate <= 100),
  creator_earnings numeric(12,2) generated always as (round(luma_net_commission * creator_share_rate / 100.0, 2)) stored,
  status text not null default 'pending' check (status in ('pending','approved','reversed','paid')),
  unique(network, external_order_id)
);

create table if not exists creator_payouts (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  creator_id uuid not null references creators(id) on delete restrict,
  period_start date not null,
  period_end date not null,
  amount numeric(12,2) not null check (amount >= 0),
  status text not null default 'pending' check (status in ('pending','processing','paid','failed')),
  paid_at timestamptz,
  notes text
);

create index if not exists referral_clicks_creator_created_idx on referral_clicks(creator_id, created_at desc);
create index if not exists attributed_sales_creator_status_idx on attributed_sales(creator_id, status);
create index if not exists creator_applications_status_idx on creator_applications(status, created_at desc);

alter table creator_applications enable row level security;
alter table creators enable row level security;
alter table referral_clicks enable row level security;
alter table attributed_sales enable row level security;
alter table creator_payouts enable row level security;

-- Public visitors should not have direct table access. The Edge Function uses the service role key.
revoke all on creator_applications from anon, authenticated;
revoke all on creators from anon, authenticated;
revoke all on referral_clicks from anon, authenticated;
revoke all on attributed_sales from anon, authenticated;
revoke all on creator_payouts from anon, authenticated;
